spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity
    username: admin
    password: 1111
    hikari:
      auto-commit: false
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # production: validate, development: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: update
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
    show-sql: false

logging:
  level:
    # Hibernate SQL 로깅
    org.hibernate.SQL: DEBUG
    # 파라미터 바인딩 값 로깅
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # 결과 추출 로깅
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    # QueryDSL 로깅
    com.querydsl.sql: DEBUG
    com.querydsl.jpa: DEBUG
    # Spring Transaction 로깅
    org.springframework.transaction: DEBUG
    # JPA Transaction 로깅
    org.springframework.orm.jpa: DEBUG