spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity
    username: admin
    password: 1111
    hikari:
      auto-commit: false
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      # 1. API 키 설정 (환경변수 사용을 강력히 권장)
      api-key: ${OPENAI_API_KEY}

      # 2. 채팅 모델 설정
      chat:
        options:
          # 사용 가능한 모델: gpt-4o, gpt-4-turbo, gpt-3.5-turbo 등
          model: gpt-4o-mini
          temperature: 0.7

      # 3. 임베딩 모델 설정
      embedding:
        options:
          # 사용 가능한 모델: text-embedding-3-small, text-embedding-3-large
          model: text-embedding-3-small

    vectorstore:
      pgvector:
        table-name: iam_vectors
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # production: validate, development: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: update
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
    show-sql: false

  jackson:
    serialization:
      fail-on-self-references: false

logging:
  level:
    # Hibernate SQL 로깅
    org.hibernate.SQL: DEBUG
    # 파라미터 바인딩 값 로깅
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # 결과 추출 로깅
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    # QueryDSL 로깅
    com.querydsl.sql: DEBUG
    com.querydsl.jpa: DEBUG
    # Spring Transaction 로깅
    org.springframework.transaction: DEBUG
    # JPA Transaction 로깅
    org.springframework.orm.jpa: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
