spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity
    username: admin
    password: 1111
    hikari:
      auto-commit: false
    driver-class-name: org.postgresql.Driver

  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        enabled: false
        options:
          model: claude-sonnet-4-20250514
          temperature: 0.3  # JSON 생성에는 낮은 temperature가 좋음

    ollama:
      base-url: http://localhost:11434
      embedding:
        enabled: true
        model: mxbai-embed-large
      chat:
        options:
          model: exaone3.5
          temperature: 0.7

    # OpenAI는 embedding용으로만 사용
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        enabled: false  # chat 비활성화, embedding만 사용
      embedding:
        enabled: false
        options:
          model: text-embedding-3-small

    vectorstore:
      pgvector:
        table-name: iam_vectors
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true
        max-document-batch-size: 10000

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # production: validate, development: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: update
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
    show-sql: false

  jackson:
    serialization:
      fail-on-self-references: false

  auth:
    mfa:
      session-timeout-ms: 600000      # 10분
      max-retry-attempts: 5
      minimum-delay-ms: 500
      circuit-breaker-failure-threshold: 5
      detailed-logging-enabled: true
      metrics-enabled: true
      audit-logging-enabled: true
      session-storage-type: redis

  cache:
    type: redis
    redis:
      cache-null-values: false # null 값 캐싱 여부
      time-to-live: 3600000 # 1시간 (밀리초)

  # Spring Data Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      #      password: # Redis 비밀번호 (필요한 경우)
      timeout: 200000
      # 연결 풀 설정
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5s
      # SSL 설정
      ssl:
        enabled: false

logging:
  level:
    # Hibernate SQL 로깅
    org.hibernate.SQL: DEBUG
    # 파라미터 바인딩 값 로깅
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # 결과 추출 로깅
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    # QueryDSL 로깅
    com.querydsl.sql: DEBUG
    com.querydsl.jpa: DEBUG
    # Spring Transaction 로깅
    org.springframework.transaction: DEBUG
    # JPA Transaction 로깅
    org.springframework.orm.jpa: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
