package io.spring.iam.domain.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

import java.util.HashMap;
import java.util.Map;

@Data
@AllArgsConstructor
public class AutoGeneratedTemplate {
    private String name;
    private String description;
    private String spelTemplate;
    private String templateType;
    private String sourceMethod;
    private boolean isUniversal;
    private Map<String, Object> metadata;

    // 생성자, getter, setter
    public AutoGeneratedTemplate(String name, String description, String spelTemplate,
                                 String templateType, String sourceMethod, boolean isUniversal) {
        this.name = name;
        this.description = description;
        this.spelTemplate = spelTemplate;
        this.templateType = templateType;
        this.sourceMethod = sourceMethod;
        this.isUniversal = isUniversal;
        this.metadata = new HashMap<>();
    }

    // Getters and Setters
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public String getSpelTemplate() { return spelTemplate; }
    public void setSpelTemplate(String spelTemplate) { this.spelTemplate = spelTemplate; }
    public String getTemplateType() { return templateType; }
    public void setTemplateType(String templateType) { this.templateType = templateType; }
    public String getSourceMethod() { return sourceMethod; }
    public void setSourceMethod(String sourceMethod) { this.sourceMethod = sourceMethod; }
    public boolean isUniversal() { return isUniversal; }
    public void setUniversal(boolean universal) { isUniversal = universal; }
    public Map<String, Object> getMetadata() { return metadata; }
    public void setMetadata(Map<String, Object> metadata) { this.metadata = metadata; }
}